document.writeln(" <div id=\"top\">");
document.writeln("        <div class=\"top_logo\"><img src=\"images/logo.png\" /> <div class=\"top_img\"><img src=\"images/linian.png\" /></div></div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div id=\"top_menu\">");
document.writeln("         <div class=\"top_text\">");
document.writeln("           <a href=\"index.html\">首页</a>　　　");
document.writeln("           <a href=\"about.html\">了解大东</a>　　　");
document.writeln("           <a href=\"service.html\">服务范围</a>　　　");
document.writeln("           <a href=\"alliance.html\">合作联盟</a>　　　");
document.writeln("           <a href=\"sales.html\">活动专区</a>　　　");
document.writeln("           <a href=\"contact.html\">联系我们</a>");
document.writeln("          </div>");
document.writeln("    </div>");
document.writeln("<div class=\"slide-main\" id=\"touchMain\">");
document.writeln("	<a class=\"prev\" href=\"javascript:;\" stat=\"prev1001\"><img src=\"images/l-btn.png\" /></a>");
document.writeln("	<div class=\"slide-box\" id=\"slideContent\">");
document.writeln("        <div class=\"slide\" id=\"bgstylee\">");
document.writeln("			<a href=\"huodong.html\"></a>");
document.writeln("		</div>");
document.writeln("		<div class=\"slide\" id=\"bgstylea\">");
document.writeln("			<a  href=\"#\">");
document.writeln("				<div class=\"obj-e\"><img src=\"images/text-1.png\" /></div>");
document.writeln("				<div class=\"obj-f\"><img src=\"images/black.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\"slide\" id=\"bgstyleb\">");
document.writeln("			<a href=\"#\">");
document.writeln("				<div class=\"obj-a\"><img src=\"images/black.png\" /></div>");
document.writeln("				<div class=\"obj-b\"><img src=\"images/text-2.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\"slide\" id=\"bgstylec\">");
document.writeln("			<a href=\"#\">");
document.writeln("				<div class=\"obj-c\"><img src=\"images/black.png\" /></div>");
document.writeln("				<div class=\"obj-d\"><img src=\"images/text-3.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("        <div class=\"slide\" id=\"bgstyled\">");
document.writeln("			<a href=\"#\">");
document.writeln("				<div class=\"obj-g\"><img src=\"images/black.png\" /></div>");
document.writeln("				<div class=\"obj-h\"><img src=\"images/text-4.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<a class=\"next\" href=\"javascript:;\" stat=\"next1002\"><img src=\"images/r-btn.png\" /></a>");
document.writeln("	<div class=\"item\">");
document.writeln("		<a class=\"cur\" stat=\"item1001\" href=\"javascript:;\"></a><a href=\"javascript:;\" stat=\"item1002\"></a><a href=\"javascript:;\" stat=\"item1003\"></a><a href=\"javascript:;\" stat=\"item1004\"></a><a href=\"javascript:;\" stat=\"item1005\"></a>");
document.writeln("	</div>");
document.writeln("</div>");