document.writeln("<div class=\"slide-main\" id=\"touchMain\">");
document.writeln("	<a class=\"prev\" href=\"javascript:;\" stat=\"prev1001\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/l-btn.png\" /></a>");
document.writeln("	<div class=\"slide-box\" id=\"slideContent\">");
document.writeln("        <div class=\"slide\" id=\"bgstylee\">");
document.writeln("			<a href=\"sales.html\"></a>");
document.writeln("		</div>");
document.writeln("		<div class=\"slide\" id=\"bgstylea\">");
document.writeln("			<a  href=\"#\">");
document.writeln("				<div class=\"obj-e\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/text-1.png\" /></div>");
document.writeln("				<div class=\"obj-f\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/black.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\"slide\" id=\"bgstyleb\">");
document.writeln("			<a href=\"#\">");
document.writeln("				<div class=\"obj-a\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/black.png\" /></div>");
document.writeln("				<div class=\"obj-b\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/text-2.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("		<div class=\"slide\" id=\"bgstylec\">");
document.writeln("			<a href=\"#\">");
document.writeln("				<div class=\"obj-c\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/black.png\" /></div>");
document.writeln("				<div class=\"obj-d\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/text-3.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("        <div class=\"slide\" id=\"bgstyled\">");
document.writeln("			<a href=\"#\">");
document.writeln("				<div class=\"obj-g\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/black.png\" /></div>");
document.writeln("				<div class=\"obj-h\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/text-4.png\" /></div>");
document.writeln("			</a>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<a class=\"next\" href=\"javascript:;\" stat=\"next1002\"><img src=\"https://cdn.jsdelivr.net/gh/dadongauto/dadongauto.github.io@main/images/r-btn.png\" /></a>");
document.writeln("	<div class=\"item\">");
document.writeln("		<a class=\"cur\" stat=\"item1001\" href=\"javascript:;\"></a><a href=\"javascript:;\" stat=\"item1002\"></a><a href=\"javascript:;\" stat=\"item1003\"></a><a href=\"javascript:;\" stat=\"item1004\"></a><a href=\"javascript:;\" stat=\"item1005\"></a>");
document.writeln("	</div>");
document.writeln("</div>");